# kind-config-simples.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster # Mudei o nome para evitar conflitos
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: ./data/worker-1
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./data/worker-2
    containerPath: /data
